/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc.lingfor;


public class App {

    public static void main(String[] args) {

        //initiate a list of users

        //generate storage token for each user

        //add token into storage instance

        //loop the list of users

        //get token for each user

        //do upload

        //assert the user is using the correct token

    }
}
