/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc.lingfor;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

        

        //loop the list of users


        //do upload

        //assert the user is using the correct token

    }
}
